"""add claim to notifications

Revision ID: 3c98c0f9b74c
Revises: d6797e94e128
Create Date: 2026-09-30 20:04:50.780678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c98c0f9b74c'
down_revision: Union[str, Sequence[str], None] = 'd6797e94e128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('claim_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notifications_claim_id'), 'notifications', ['claim_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'claims', ['claim_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_claim_id'), table_name='notifications')
    op.drop_column('notifications', 'claim_id')
    # ### end Alembic commands ###
