"""make claim match unique

Revision ID: d6797e94e128
Revises: 305e0c2bc3be
Create Date: 2026-09-30 10:08:49.980295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6797e94e128'
down_revision: Union[str, Sequence[str], None] = '305e0c2bc3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_match_id'), table_name='claims')
    op.create_index(op.f('ix_claims_match_id'), 'claims', ['match_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_match_id'), table_name='claims')
    op.create_index(op.f('ix_claims_match_id'), 'claims', ['match_id'], unique=False)
    # ### end Alembic commands ###
