"""add item embeddings

Revision ID: dadaa56d2669
Revises: 9203a4c9ebd9
Create Date: 2026-09-23 20:21:23.855418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'dadaa56d2669'
down_revision: Union[str, Sequence[str], None] = '9203a4c9ebd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_embeddings_id'), 'item_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_item_embeddings_item_id'), 'item_embeddings', ['item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_embeddings_item_id'), table_name='item_embeddings')
    op.drop_index(op.f('ix_item_embeddings_id'), table_name='item_embeddings')
    op.drop_table('item_embeddings')
    # ### end Alembic commands ###
